start_message = """Hi. Please send CV in .pdf format for analyzing by bot. By using this product, you are agreeing to share data."""
started_processing_message = "Started process of analyzing {} file"

general_caption = " Text highlighted in <b>{}</b> color are considered as generated by AI with probability {}"
fabricated_entities_caption = "Text highlighted In <b>RED</b> color are considered as fabricated entities and are checked upon external sources"
start_results_caption = "Here is interpretation of the resume analysis by CV Analyzer Bot:"
end_results_caption = "Please note that the classification results from  this bot may not always be entirely accurate."
